version: '3'
services:
 
  spring-app:
    image: 'jhonyamn/mustang:1.2b'
    ports:
      - '8080:8080'
    environment:
      - 'DATABASE_URL=jdbc:mysql://srv-mysql-senac69.mysql.database.azure.com:3306/mustang?createDatabaseIfNotExist=true'
      - 'SPRING_DATASOURCE_USERNAME=luhera'
      - 'SPRING_DATASOURCE_PASSWORD=Dinho-heraclio1'
    networks:
      - mynetwork

  front-app:
    image: 'jhonyamn/nascar:1.0'
    ports:
      - '5173:5173'
    environment:
      - 'VITE_API_URL=http://127.0.0.1:8080'  # Use o nome do serviço e a porta para acessar o spring-app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge